# Generated by Django 3.2.13 on 2022-04-25 08:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Введите номер телефона в формате 7XXXXXXXXXX(X - цифра от 0 до 9)', regex='^7\\w{10}$')])),
                ('tag', models.CharField(blank=True, max_length=20, verbose_name='Тэг')),
                ('timezone', models.IntegerField(verbose_name='Часовой пояс')),
                ('mobile_operator_code', models.CharField(blank=True, max_length=3, verbose_name='Код оператора связи')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Начало рассылки')),
                ('stop_datetime', models.DateTimeField(verbose_name='Окончание рассылки')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('mobile_operator_code', models.CharField(blank=True, max_length=3, verbose_name='Код оператора связи')),
                ('tag', models.CharField(blank=True, max_length=20, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('status', models.CharField(choices=[('OK', 'Message sent'), ('SC', 'Scheduled'), ('ER', 'An error has occurred'), ('FA', 'Sending failed')], max_length=20, verbose_name='Статус отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='api.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.mailing')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
